### PR TITLE
Dev

### LINKED ISSUE #75: [FEATURE REQUEST] Add "Back to Top" Button to the Website
The website currently lacks a "Back to Top" button, which can improve user experience by allowing users to quickly scroll back to the top of the page. This is especially useful for pages with a lot of content that require extensive scrolling.

Be hidden by default and only appear after a certain scroll threshold (e.g., 200px down the page).
Include smooth scroll behavior to enhance user experience.
Be responsive and compatible with both light and dark themes.

please assign this issue to me @Puskar-Roy under gssoc-ext and hacktoberfest

### PR DESCRIPTION
**Pull request by sezallagwal**
# 🎯 Title and Issue Number

### Closes #75 

# 🗒️ Checklist:

- [] I have mentioned the issue number in my Pull Request.
- []  I have gone through `rules of when PR will get merged.` 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have followed proper file structure.
- [] I have gone through

 Thank you for contributing!❤️ 

Don't forget to show some support by ⭐ the repository!

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @sezallagwal, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by Puskar-Roy** [comment]
@sezallagwal make the pr in ```dev``` branch

**Comment by sezallagwal** [comment]
@Puskar-Roy I have done it, you can check

**Comment by Puskar-Roy** [comment]
Hey @sezallagwal! We're excited to let you know that your pull request has been merged into the APIverse🚀🎁
Your commitment, effort, and expertise have greatly influenced our project, and we're incredibly thankful for your contributions.😇
Your code is now part of our expanding ecosystem, assisting developers worldwide in creating exceptional APIs.❣️🔥
Happy Coding! ✨ We look forward to seeing you again soon!❣️

**Pull request merged**
