### PR TITLE
fixed ui

### LINKED ISSUE #74: UI issue
### API Summary 📝

The current UI of scrolling is not working properly, its too down and its not visible properly

https://github.com/user-attachments/assets/a5b8a2c5-fe05-4e97-ba95-16103e6043e6

### Development Approach 🚀

the UI should be properly visible

### Deployment Status

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Sourabh782**
# 🎯 Title and Issue Number

### Closes #74 

# 🗒️ Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X]  I have gone through `rules of when PR will get merged.` 
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have followed proper file structure.
- [X] I have gone through

https://github.com/user-attachments/assets/742929fd-42b9-44d3-906a-e189a7835634

 Thank you for contributing!❤️ 

Don't forget to show some support by ⭐ the repository!

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @Sourabh782, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by Puskar-Roy** [comment]
@Sourabh782 please send pr in the ```dev``` branch

**Comment by Sourabh782** [comment]
Sure @Puskar-Roy

**Comment by Puskar-Roy** [comment]
Hey @Sourabh782! We're excited to let you know that your pull request has been merged into the APIverse🚀🎁
Your commitment, effort, and expertise have greatly influenced our project, and we're incredibly thankful for your contributions.😇
Your code is now part of our expanding ecosystem, assisting developers worldwide in creating exceptional APIs.❣️🔥
Happy Coding! ✨ We look forward to seeing you again soon!❣️

**Pull request merged**
