### PR TITLE
Feature/GitHub stars mobile view

### LINKED ISSUE #34: [WEB Improvement] : The github stars section is disappearing in mobile view
### Quick Description 🛠️

https://github.com/user-attachments/assets/5272f23e-c00c-4917-86b1-6ab81091aacf

I am eager to start working on it , could you please assign it to me?

### Select the open-source program you're contributing to

Other

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by ShivanshPlays**
# 🎯 Title and Issue Number

### Closes #34 

# 🗒️ Checklist:

- [1] I have mentioned the issue number in my Pull Request.
- [1]  I have gone through `rules of when PR will get merged.` 
- [1] I have commented my code, particularly in hard-to-understand areas
- [1] I have created a helpful and easy to understand `README.md`
- [1] I have followed proper file structure.
- [1] I have gone through

 Thank you for contributing!❤️ 

Don't forget to show some support by ⭐ the repository!

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @ShivanshPlays, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by Puskar-Roy** [comment]
Hey @ShivanshPlays! We're excited to let you know that your pull request has been merged into the APIverse🚀🎁
Your commitment, effort, and expertise have greatly influenced our project, and we're incredibly thankful for your contributions.😇
Your code is now part of our expanding ecosystem, assisting developers worldwide in creating exceptional APIs.❣️🔥
Happy Coding! ✨ We look forward to seeing you again soon!❣️

**Comment by ShivanshPlays** [comment]
Hi @Puskar-Roy , can you please assign the tags to this PR so that my efforts are reflected. 

[gssoc-ext](https://github.com/Puskar-Roy/create-my-api/labels/gssoc-ext)
[hacktoberfest](https://github.com/Puskar-Roy/create-my-api/labels/hacktoberfest)
[hacktoberfest-accepted](https://github.com/Puskar-Roy/create-my-api/labels/hacktoberfest-accepted)
[level1](https://github.com/Puskar-Roy/create-my-api/labels/level1)

**Comment by Puskar-Roy** [comment]
@ShivanshPlays Apologies 🥲

**Comment by ShivanshPlays** [comment]
Thankyou! :)

**Comment by ShivanshPlays** [comment]
I think you forgot to assign me on this PR

**Pull request merged**
