### PR TITLE
enhanced contact form

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
# 🎯 Title and Issue Number
@Puskar-Roy 
I have enhanced the contact us section
If you like it, please consider it as level3 and i made it responsive too
Kindly check it out

https://github.com/user-attachments/assets/ee3311a1-5e01-423a-a1fd-8db5d325b535

### Closes #<issue_no>

# 🗒️ Checklist:

- [] I have mentioned the issue number in my Pull Request.
- []  I have gone through `rules of when PR will get merged.` 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have followed proper file structure.
- [] I have gone through

 Thank you for contributing!❤️ 

Don't forget to show some support by ⭐ the repository!

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @AswaniBolisetti, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please merge this PR with label 3

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please merge this

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please merge this

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please merge this

**Review by Puskar-Roy — CHANGES_REQUESTED** [review]
hey sorry for late response, you need raise pr in ```dev``` branch

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy check now once please

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please merge this

**Review by Puskar-Roy — APPROVED** [review]

**Pull request merged**
