### PR TITLE
enhanced scroll to top

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@Puskar-Roy 
I have enhanced the scroll to top feature and added some bouncing animation to it
Kindly check it out

From this 

scrollold mp4

to this

https://github.com/user-attachments/assets/e127f80d-6096-46b4-a757-e36398697cbd

Issue no : #140

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @AswaniBolisetti, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by Puskar-Roy** [comment]
@AswaniBolisetti make pr in dev branch

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please check now, changed to dev

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please merge this

**Pull request merged**
