### PR TITLE
added scroll progress bar

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@Puskar-Roy 
I have created scroll progress bar successfully
Kindly check it out

https://github.com/user-attachments/assets/007a76e9-d12a-4b34-a6df-0adf0363ef1a

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @AswaniBolisetti, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy could you please review and merge it if you like

**Comment by Puskar-Roy** [comment]
@AswaniBolisetti hey everything is great, can you please raise this pr in ```dev``` branch.

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
I changed the branch to dev
Could you please check it now

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Could you please check now

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Kindly review and merge it

**Pull request merged**
