### PR TITLE
Added contact us form

### LINKED ISSUE #120: Add contact us form
### Quick Description 🛠️

I want to set up contact us page and a contact us form so that users can reach out when they r facing issues

@Puskar-Roy please assign me this issue with level 2, gssoc-extd, hacktoberfest

### Select the open-source program you're contributing to

GSSOC 2024 EXTD, Hacktoberfest 2024

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by meghanakn473**
# 🎯 Title and Issue Number

Contact us form: helps user to reach out the admins

### Closes #120 

# 🗒️ Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X]  I have gone through `rules of when PR will get merged.` 
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have followed proper file structure.
- [X] I have gone through

 Thank you for contributing!❤️ 

Don't forget to show some support by ⭐ the repository!

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @meghanakn473, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by meghanakn473** [comment]
@Puskar-Roy please review and allow merge
also please add all the labels,,,level 3,gssoc-extd, hacktoberfest for my implementation of backend and frontend

**Comment by meghanakn473** [comment]
https://github.com/user-attachments/assets/f931a950-ef41-4f6f-ac8a-bf2774e696e5

here is the proof of wt i have implemented

**Comment by meghanakn473** [comment]
@Puskar-Roy please review and allow merge
also please add all the labels,,,level 3,gssoc-extd, hacktoberfest for my implementation of backend and frontend

**Review by Puskar-Roy — CHANGES_REQUESTED** [review]
Change The UI, the UI is not match with the current website and make pr in dev branch

**Comment by meghanakn473** [comment]
> Change The UI, the UI is not match with the current website and make pr in dev branch
Can u describe wt ui r u expecting?
So that I can make according to it

**Comment by Puskar-Roy** [comment]
> > Change The UI, the UI is not match with the current website and make pr in dev branch
> 
> @Puskar-Roy Can u describe wt ui r u expecting? So that I can make according to it

@meghanakn473  you can see the theme of our website, and make a form that match with it.

**Comment by meghanakn473** [comment]
@Puskar-Roy please check i have modified the theme accordingly
Screenshot (190)

**Comment by Puskar-Roy** [comment]
> @Puskar-Roy please check i have modified the theme accordingly Screenshot (190)

great! now please raise this pr into ```dev``` branch

**Review by Puskar-Roy — APPROVED** [review]

**Comment by meghanakn473** [comment]
@Puskar-Roy hey can u guide me how can i raise pr in dev branch

**Comment by Puskar-Roy** [comment]
> @Puskar-Roy hey can u guide me how can i raise pr in dev branch

Go to the repository on GitHub, then create a new Pull Request (PR). Select your branch (my-feature-branch) as the source, and the ```dev``` branch as the target.  then submit the PR
Screenshot from 2024-10-22 23-29-52
.

**Pull request closed without merging**
