### PR TITLE
added cursor animation

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
I have added the cursor animation

cursorImage

https://github.com/user-attachments/assets/e023a209-fb55-4ae2-8fce-2e348eceffeb

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @AswaniBolisetti, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by Puskar-Roy** [comment]
@AswaniBolisetti Please send pr in ```dev``` branch

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy Yes I have changed it

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy could you please merge this, dont delete

**Comment by Puskar-Roy** [comment]
@AswaniBolisetti my bad my bad

**Comment by Puskar-Roy** [comment]
Hey @AswaniBolisetti! We're excited to let you know that your pull request has been merged into the APIverse🚀🎁
Your commitment, effort, and expertise have greatly influenced our project, and we're incredibly thankful for your contributions.😇
Your code is now part of our expanding ecosystem, assisting developers worldwide in creating exceptional APIs.❣️🔥
Happy Coding! ✨ We look forward to seeing you again soon!❣️

**Comment by AswaniBolisetti** [comment]
Thank you so much

**Pull request merged**
