### PR TITLE
added terms and conditions page

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@Puskar-Roy 
I have added terms and conditions page
Kindly check it out

https://github.com/user-attachments/assets/5cc194c6-38c5-49f1-ae0d-3c27a1e82e4a

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @AswaniBolisetti, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Review by Puskar-Roy — CHANGES_REQUESTED** [review]
please make this page responsive for mobile view
Screenshot from 2024-10-22 22-12-33
Screenshot from 2024-10-22 22-12-42

**Review by Puskar-Roy — APPROVED** [review]

**Comment by Puskar-Roy** [comment]
> @Puskar-Roy Now added mobile view Kindly check it out
> 
> img1
> 
> img2
> 
>  mobileterms.mp4

great but raise pr in ```dev``` branch

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Done
Check it once

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Could you please check it once

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Could you please review and merge it
please

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please review it

**Comment by Puskar-Roy** [comment]
@AswaniBolisetti please solve the conflict

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Could you please check now

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Could you please check now i have resolved the conflicts

**Comment by AswaniBolisetti** [comment]
Sorry unfortunately I have deleted this
I'll create another pr

**Pull request closed without merging**
