### PR TITLE
improve mobile responsiveness

### PR DESCRIPTION
**Pull request by Joshna907**
#71 done
please do connect my pull request I have made the necessary changes

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @Joshna907, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by Puskar-Roy** [comment]
@Joshna907 please push code into the ```dev``` Branch

**Comment by Joshna907** [comment]
idk why im getting an error please do check it in main

**Comment by Puskar-Roy** [comment]
@Joshna907 nope it is not possible for me to accept the pr in directly ```main```   branch :(
please raise a pr in ```dev``` branch

**Pull request closed without merging**
