### PR TITLE
feat:Dynamic repo star count added using the github api

### LINKED ISSUE #35: [WEB Improvement] : Add Dynamic GitHub Stars Section ⭐
### Quick Description 🛠️

Currently all the Github Starts that shown in The Website is Static, make it Dynamic Github Stars
Screenshot_2024-10-02-07-27-46-066_com android chrome-edit

### Select the open-source program you're contributing to

Other

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by South-IN**
# 🎯[WEB Improvement] : Add Dynamic GitHub Stars Section #35 

### Closes #35 
# Description of changes :
- I created a state for the GitHub stars of the repo.
- fetched the repo data using the GitHub API.
- set the state of stars as the repo's stargazers_count
- displayed the stars.

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @South-IN, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by South-IN** [comment]
What is the issue with vercel ?
i cant see the details. 
the changesshow no error locally.

**Comment by South-IN** [comment]
can i see the logs @Puskar-Roy ?

**Comment by Puskar-Roy** [comment]
@South-IN 
Screenshot from 2024-10-03 11-57-43

**Comment by Puskar-Roy** [comment]
@South-IN Great but please Push into dev branch

**Pull request closed without merging**
