### PR TITLE
added cursor animation

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
# 🎯 Title and Issue Number
@Puskar-Roy 
I have added cursor animation successfully and made it align with the website styling
If you like to please consider it as level2 or level3
Kindly check it out

https://github.com/user-attachments/assets/b4d4a37d-2ad3-4aae-a43c-9113035b9d00

### Closes #<issue_no>

# 🗒️ Checklist:

- [] I have mentioned the issue number in my Pull Request.
- []  I have gone through `rules of when PR will get merged.` 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have followed proper file structure.
- [] I have gone through

 Thank you for contributing!❤️ 

Don't forget to show some support by ⭐ the repository!

### CODE REVIEW

**Comment by Puskar-Roy** [comment]
Hello @AswaniBolisetti, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please merge this

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please merge this

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy 
Please merge this one

**Pull request closed without merging**
